Repository SovereignCloudStack/docs, pull requests merged in 2023-09, with the labels that each got.

#73 Readd (old) testbed and ciab docs as 02-iaas/deployment-examples.
  .gitignore
  docs.package.json
  docs/02-iaas/deployment-examples/a/hardware.md
  docs/02-iaas/deployment-examples/a/index.md
  docs/02-iaas/deployment-examples/a/software.md
  docusaurus.config.js
  sidebarsDocs.js
Labels: bug, documentation

#75 Add release 5 to docs.
  index.md
  sidebarsDocs.js
Labels: documentation

#77 Request cloud resource
  community/cloud-resources/cloud-resources.md
Labels: SCS-VP10
