Repository SovereignCloudStack/docs, pull requests merged in 2024-03, with the labels that each got.

#152 Add missing k8s-cluster-api-provider doc pages
  sidebarsDocs.js
Labels: documentation

#160 Adjust populateStds.js and populateCerts.js to renamed field
  populateCerts.js
  populateStds.js
Labels: SCS is standardized, SCS-VP10

#155 Add OS Health Mon setup guide.
  .gitignore
  docs.package.json
  docs/04-operating-scs/01-guides/guide-1.md
  sidebarsDocs.js
Labels: documentation, enhancement, work in progress

#164 Link to v2 test for PCO1,2,3. Add PCO4 and AOV.
  standards/certification/overview.md
Labels: bug, enhancement, standards

#169 Add R6 release notes and ref R6 as latest.
  sidebarsDocs.js
  static/data/featureContentData.json
Labels: documentation, enhancement, housekeeping

#163 Rename Domain Manager role and adjust admonitions
  docs/05-iam/domain-manager-setup-and-usage.md
Labels: SCS-VP10
