Repository SovereignCloudStack/docs, pull requests merged in 2024-08, with the labels that each got.

#218 Refresh clouds table once again
  standards/certification/overview.md
Labels: SCS is standardized, SCS-VP10

#219 Upgrade k8s that hosts SCS monitoring to R6
  community/central-services/plusserver-gx-scs.md
Labels: documentation

#220 Simplify standards overview table
  populateStds.js
Labels: SCS is standardized, SCS-VP10

#223 include SCS Health Monitor .md docs
  docs.package.json
  sidebarsDocs.js
  static/data/architecturalOverviewData.json
Labels: SCS-VP12
