Repository SovereignCloudStack/docs, pull requests merged in 2024-09, with the labels that each got.

#242 feat(security): Add KaaS pentesting tools to docs
  docs.package.json
  sidebarsDocs.js
  static/data/architecturalOverviewData.json
Labels: security

#244 Reenable link to gxscs-hm. It's working reliably.
  standards/certification/overview.md
Labels: housekeeping

#252 Fix/update ws, path-to-regexp, micromatch
  package-lock.json
Labels: housekeeping, security

#254 Update caniuse-lite (browsersl.ist)
  package-lock.json
  package.json
Labels: housekeeping

#257 Fix link to repo
  community/contribute/adding-docs-guide.md
Labels: housekeeping
